export const ADD_TO_CART_ITEM = "ADD_TO_CART_ITEM";
export const REMOVE_FROM_CART_ITEM = "REMOVE_FROM_CART_ITEM";
export const RESET_CART_ITEM = "RESET_CART_ITEM";
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_SHIPPING_ADDRESS";
